pluginManagement {
    repositories {
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "MARCaribe"
include ':app'
// ⚠️ NO incluimos capacitor-android aquí — lo agrega `npx cap sync` automáticamente

